name: Daily Cleanup
on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 1 AM UTC every day
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call cleanup endpoint
        run: |
          curl --request POST \
          --url 'https://share.levine.io/api/v1/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
