name: Playwright Tests Published

on:
  deployment_status:

jobs:
  run-e2e-published:
    name: Run end-to-end tests on published site
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        env:
          PUBLIC_ENV: preview
          VERCEL_URL: ${{ github.event.deployment_status.target_url }}
      - name: Create folder for artifacts
        run: mkdir -p playwright-report/published
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-published
          path: playwright-report/published/
