name: Playwright Tests

on:
  deployment_status:

jobs:
  run-e2es:
    name: Run end-to-end tests
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        env:
          PUBLIC_ENV: CI
          VERCEL_URL: ${{ github.event.deployment_status.target_url }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
